redis:
  image: redis:3-alpine

mongo:
  image: mongo:3

postgres:
  image: postgres:9
  environment:
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_DB=$POSTGRES_DB

graphql:
  image: $DOCKER_ACCOUNT/graphql
  ports:
    - "$GRAPHQL_SERVER_PORT:$GRAPHQL_SERVER_PORT"
  links:
    - redis:redis
    - mongo:mongo
    - postgres:postgres
  environment:
    - NODE_ENV=production
    - PORT=$GRAPHQL_SERVER_PORT
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - MONGO_HOST=mongo
    - MONGO_PORT=27017
    - MONGO_DB=$GRAPHQL_MONGO_DB
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_DB=$POSTGRES_DB
    - JWT_SECRET=geqaihv3uf893qu89ghiooigd

client:
  image: $DOCKER_ACCOUNT/client
  ports:
    - "$CLIENT_SERVER_PORT:$CLIENT_SERVER_PORT"
  links:
    - api:api
  environment:
    - NODE_ENV=production
    - PORT=$CLIENT_SERVER_PORT
    - GRAPHQL_FQDN=http://graphql:$GRAPHQL_SERVER_PORT
  - BROWSER_GRAPHQL_FQDN=http://localhost:$GRAPHL_SERVER_PORT
    - ASSETS_FQDN=https://assets.jobstart.com
