redis:
  image: redis:3-alpine
  ports:
    - "$REDIS_PORT:6379"

mongo:
  image: mongo:3
  ports:
    - "$MONGO_PORT:27017"

postgres:
  image: postgres:9
  environment:
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_DB=$POSTGRES_DB
  ports:
    - "$POSTGRES_PORT:5432"
